name: Integration tests

on:
  push:
    branches: [ Develop, main ]
  pull_request:
    branches: [ Develop, main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      sql.data:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: P@$$w0rd
          ACCEPT_EULA: Y
        ports:
          - "1433:1433"

    steps:
    - uses: actions/checkout@v2
        
    - name: Replace connection string by MSSQL in container
      uses: microsoft/variable-substitution@v1
      with:
        files: ./ProjectManagement/ProjectManagementApi/appsettings.IntegrationTests.json
      env:
        ConnectionStrings.DefaultConnection: Server=localhost,1433; Database=ProjectManagementDB; User Id='SA'; Password='P@$$w0rd'
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./ProjectManagement/tests/ProjectManagementApi.IntegrationTests

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./ProjectManagement/tests/ProjectManagementApi.IntegrationTests

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./ProjectManagement/tests/ProjectManagementApi.IntegrationTests