name: Build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
          
      - uses: microsoft/variable-substitution@v1
        with:
          files: "ProjectManagement/ProjectManagementApi/appsettings.json"
        env:
          ApplicationInsights.InstrumentationKey: ${{ secrets.INSTRUMENTATION_KEY }}
          ConnectionStrings.DefaultConnection: ${{ secrets.PRODUCTION_CONNECTION_STRING }}
          EmailProvider.SendGridApiKey: ${{ secrets.SENDGRID_KEY }}
          EmailProvider.ConfirmMessageId: ${{ secrets.SENDGRID_CONFIRM_KEY }}
          EmailProvider.ResetEmailMessageId: ${{ secrets.SENDGRID_RESET_EMAIL_KEY }}
          EmailProvider.ResetPasswordMessageId: ${{ secrets.SENDGRID_RESET_PASSWORD_KEY }}
            
      - name: Read appsettings.json
        run: "cat ProjectManagement/ProjectManagementApi/appsettings.json"

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ./ProjectManagement/ProjectManagementApi

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
        working-directory: ./ProjectManagement/ProjectManagementApi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pm-asystent'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_13F576B651F14457B87DDA5C732A4063 }}
          package: .
